"""
Known-answer studies for AdsorpQC 1.1 against the 1.0.0 behaviour.

1. Drift test. Stationary series (no drift) and series with a linear drift of known size, for the two
   regimes met in GCMC: high loading with small relative noise (AR(1), phi = 0.5, CV 5%), and low
   loading with Poisson counts (mean 2 molecules, CV 71%). Series of 40 and 400 samples.
   Rates of FAIL and of FAIL-or-WARNING from assess_loading_drift of 1.1 and of 1.0.0.
2. Isotherm model selection. Seven (or twelve) pressures, 1% Gaussian noise, data generated by a
   Langmuir or by a dual-site Langmuir isotherm; how often the plain AIC and the AICc select each model.

Usage: python known_answer_studies.py OUT_DIR [--reps 1000]
"""
import argparse
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.path.insert(0, HERE)
from adsorpqc.core.burnin import assess_loading_drift                 # noqa: E402
from adsorpqc.core.isotherms import fit_all_isotherm_models           # noqa: E402
from legacy_v100 import burnin_v100                                    # noqa: E402

K_PARAMS = {"Langmuir": 2, "Dual-Site Langmuir": 4, "Sips": 3, "Toth": 3}


def series(rng, kind, n, drift):
    if kind == "high loading (AR(1), CV 5%)":
        e = np.empty(n)
        e[0] = rng.normal()
        for t in range(1, n):
            e[t] = 0.5 * e[t - 1] + np.sqrt(1 - 0.25) * rng.normal()
        base = 1.0 + 0.05 * e
    else:
        base = rng.poisson(2.0, n).astype(float) / 2.0          # mean 1, CV 0.71
    ramp = 1.0 + drift * (np.arange(n) / (n - 1) - 0.5)       # total change = drift x mean
    return base * ramp


def drift_study(reps, seed=11):
    rng = np.random.default_rng(seed)
    rows = []
    for kind in ("high loading (AR(1), CV 5%)", "low loading (Poisson, mean 2)"):
        for n in (40, 400):
            for drift in (0.0, 0.05, 0.20, 0.50):
                st_new, st_old = [], []
                for _ in range(reps):
                    y = series(rng, kind, n, drift)
                    st_new.append(assess_loading_drift(y)[3])
                    st_old.append(burnin_v100.assess_loading_drift(y)[3])
                for ver, st in (("1.1", st_new), ("1.0.0", st_old)):
                    st = np.array(st)
                    rows.append({"regime": kind, "n": n, "drift": drift, "version": ver,
                                 "fail_rate": float(np.mean(st == "FAIL")),
                                 "flag_rate": float(np.mean(st != "PASS")), "reps": reps})
    return pd.DataFrame(rows)


def model_study(reps, seed=12):
    rng = np.random.default_rng(seed)
    truths = {
        "Langmuir": lambda p: 3.0 * p / (1 + p),
        "Dual-Site Langmuir": lambda p: 1.5 * 10 * p / (1 + 10 * p) + 2.0 * 0.3 * p / (1 + 0.3 * p),
    }
    rows = []
    for truth, f in truths.items():
        for npts in (7, 12):
            p = np.logspace(-2, 1.3, npts)
            q0 = f(p)
            picks = {"AIC": [], "AICc": []}
            for _ in range(reps):
                q = q0 + rng.normal(0, 0.01 * q0.max(), npts)
                r = fit_all_isotherm_models(p, q)
                models = r["models"]
                if not models:
                    continue
                aicc = {k: m.aic for k, m in models.items()}
                aic = {}
                for k, m in models.items():
                    kk = K_PARAMS[k]
                    aic[k] = m.aic - 2 * kk * (kk + 1) / (npts - kk - 1) if np.isfinite(m.aic) else np.inf
                picks["AICc"].append(min(aicc, key=aicc.get))
                picks["AIC"].append(min(aic, key=aic.get))
            for crit, pk in picks.items():
                pk = pd.Series(pk)
                for model in K_PARAMS:
                    rows.append({"truth": truth, "points": npts, "criterion": crit, "selected": model,
                                 "fraction": float((pk == model).mean()), "reps": len(pk)})
    return pd.DataFrame(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--reps", type=int, default=1000)
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    d = drift_study(a.reps)
    d.to_csv(os.path.join(a.out, "drift_study.csv"), index=False)
    print(d.pivot_table(index=["regime", "n", "drift"], columns="version", values=["fail_rate", "flag_rate"]).round(3))
    m = model_study(max(200, a.reps // 2))
    m.to_csv(os.path.join(a.out, "model_selection_study.csv"), index=False)
    print(m.pivot_table(index=["truth", "points", "criterion"], columns="selected", values="fraction").round(3))


if __name__ == "__main__":
    main()
